### ISSUE TITLE
Gazetteer review

### ISSUE THREAD

**Issue by itcareerswitch** [vickyprogrammer/gazetteer#1]
- [x] #2
- [x] Too much customisation of select - United Kingdom at top and disabled
- [x] The select doesn't change value to the derived country on load. Pass the navigator.position coords via AJAX to a PHP routine that calls the GeoNames CountryCodeJSON API. It will return a country code - use it to change the value of the country select and fire the event handler: document.getElementById('countrySelect').value="GB" (fire change event)
- [x] Leaflet Extra Markers would have been easier to implement and given better results: https://codepen.io/itcareerswitch/pen/MWBgjGy/b7a8809a112eb804fbb659952e2a19f2
- [x] Time zone is two words: What about countries with more than one zone?
- [x] Format all dates and numbers ([dateJS](https://github.com/datejs/Datejs) & [numeralJS](http://numeraljs.com/))
- [x] Weather example: https://codepen.io/itcareerswitch/pen/vYzEBvX/58fd2357741ed73196232e5d295850e8
- [x] News example: https://codepen.io/itcareerswitch/pen/OJaypBQ/01f42a51bbea244d756dcbaf9496c1e5
- [x] Currency example: https://codepen.io/itcareerswitch/pen/dygBBam/a9c69b65f132c1f17c2552e72a244238
- [x] Add public holidays
- [x] Do not use CDNs
- [x] Declare only CSS in head tag - JS must be declared before end body tag. Own files declared last in each section
- [x] Clear console of all logs and errors

**Comment by vickyprogrammer** [comment]
All tasks completed
